// <auto-generated />
using System;
using AarhusSpaceProgram.MissionManagement.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AarhusSpaceProgram.MissionManagement.Api.Migrations
{
    [DbContext(typeof(MissionManagementDbContext))]
    [Migration("20260416104824_Identity")]
    partial class Identity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Astronaut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HoursInSimulation")
                        .HasColumnType("int");

                    b.Property<int>("HoursInSpace")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Paygrade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Astronauts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoursInSimulation = 500,
                            HoursInSpace = 100,
                            Name = "Neil Legstrong",
                            Paygrade = "2-A",
                            Rank = "Astronaut"
                        },
                        new
                        {
                            Id = 2,
                            HoursInSimulation = 600,
                            HoursInSpace = 150,
                            Name = "Buzz Lightyear",
                            Paygrade = "3-A",
                            Rank = "Pilot"
                        },
                        new
                        {
                            Id = 3,
                            HoursInSimulation = 700,
                            HoursInSpace = 200,
                            Name = "Sally Ride",
                            Paygrade = "3-A",
                            Rank = "MissionSpecialist"
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanceValueToParentAU")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PlanetClass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CelestialBodies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyType = "Planet",
                            DistanceValueToParentAU = 1.0,
                            Name = "Earth",
                            PlanetClass = "Rocky"
                        },
                        new
                        {
                            Id = 2,
                            BodyType = "Moon",
                            DistanceValueToParentAU = 0.0025699999999999998,
                            Name = "Moon",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            BodyType = "Planet",
                            DistanceValueToParentAU = 1.524,
                            Name = "Mars",
                            PlanetClass = "Rocky"
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Launchpad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxSupportedWeightKg")
                        .HasColumnType("int");

                    b.Property<string>("PadCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PadCode")
                        .IsUnique();

                    b.ToTable("Launchpads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Kennedy Space Center, Florida, USA",
                            MaxSupportedWeightKg = 63800,
                            PadCode = "LC-39A",
                            Status = "Operational"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Cape Canaveral Space Force Station, Florida, USA",
                            MaxSupportedWeightKg = 17440,
                            PadCode = "SLC-41",
                            Status = "UnderMaintenance"
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dean Kranz"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ellen Ripley"
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CelestialBodyId")
                        .HasColumnType("int");

                    b.Property<int?>("DurationHours")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LaunchDate")
                        .HasColumnType("date");

                    b.Property<int?>("LaunchpadId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RocketId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CelestialBodyId");

                    b.HasIndex("LaunchpadId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RocketId");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationHours = 4872,
                            LaunchDate = new DateOnly(2020, 7, 30),
                            Name = "Mars 2020",
                            Status = "Completed",
                            Type = "Landing"
                        },
                        new
                        {
                            Id = 2,
                            DurationHours = 613,
                            LaunchDate = new DateOnly(2022, 11, 16),
                            Name = "Artemis I",
                            Status = "Completed",
                            Type = "Orbit"
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.MissionAstronautAssignment", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("AstronautId")
                        .HasColumnType("int");

                    b.HasKey("MissionId", "AstronautId");

                    b.HasIndex("AstronautId");

                    b.ToTable("MissionAstronautAssignments");

                    b.HasData(
                        new
                        {
                            MissionId = 1,
                            AstronautId = 1
                        },
                        new
                        {
                            MissionId = 1,
                            AstronautId = 2
                        },
                        new
                        {
                            MissionId = 2,
                            AstronautId = 3
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.MissionScientistAssignment", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("ScientistId")
                        .HasColumnType("int");

                    b.HasKey("MissionId", "ScientistId");

                    b.HasIndex("ScientistId");

                    b.ToTable("MissionScientistAssignments");

                    b.HasData(
                        new
                        {
                            MissionId = 1,
                            ScientistId = 1
                        },
                        new
                        {
                            MissionId = 2,
                            ScientistId = 2
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Rocket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrewCapacity")
                        .HasColumnType("int");

                    b.Property<int>("FuelCapacityKg")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumberOfStages")
                        .HasColumnType("int");

                    b.Property<int>("PayloadCapacityKg")
                        .HasColumnType("int");

                    b.Property<int>("WeightKg")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rockets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CrewCapacity = 0,
                            FuelCapacityKg = 284000,
                            Name = "Atlas V 541",
                            NumberOfStages = 2,
                            PayloadCapacityKg = 17440,
                            WeightKg = 49000
                        },
                        new
                        {
                            Id = 2,
                            CrewCapacity = 4,
                            FuelCapacityKg = 2500000,
                            Name = "Space Launch System Block 1",
                            NumberOfStages = 2,
                            PayloadCapacityKg = 95000,
                            WeightKg = 130000
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Scientist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Scientists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HireDate = new DateTime(2010, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Howard Wolowitz",
                            Specialty = "Rocket Propulsion",
                            Title = "Aerospace Engineer"
                        },
                        new
                        {
                            Id = 2,
                            HireDate = new DateTime(2012, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Werner von Schwartz",
                            Specialty = "Planetary Science",
                            Title = "Astrophysicist"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", "TargetBody")
                        .WithMany("TargetedByMissions")
                        .HasForeignKey("CelestialBodyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Launchpad", "Launchpad")
                        .WithMany("Missions")
                        .HasForeignKey("LaunchpadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Manager", "Manager")
                        .WithMany("Missions")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Rocket", "Rocket")
                        .WithMany("Missions")
                        .HasForeignKey("RocketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Launchpad");

                    b.Navigation("Manager");

                    b.Navigation("Rocket");

                    b.Navigation("TargetBody");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.MissionAstronautAssignment", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Astronaut", "Astronaut")
                        .WithMany("MissionAssignments")
                        .HasForeignKey("AstronautId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", "Mission")
                        .WithMany("AstronautAssignments")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Astronaut");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.MissionScientistAssignment", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", "Mission")
                        .WithMany("ScientistAssignments")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Scientist", "Scientist")
                        .WithMany("MissionAssignments")
                        .HasForeignKey("ScientistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Scientist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Astronaut", b =>
                {
                    b.Navigation("MissionAssignments");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("TargetedByMissions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Launchpad", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Manager", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", b =>
                {
                    b.Navigation("AstronautAssignments");

                    b.Navigation("ScientistAssignments");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Rocket", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Scientist", b =>
                {
                    b.Navigation("MissionAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
