// <auto-generated />
using System;
using AarhusSpaceProgram.MissionManagement.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AarhusSpaceProgram.MissionManagement.Api.Migrations
{
    [DbContext(typeof(MissionManagementDbContext))]
    partial class MissionManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Astronaut", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HoursInSimulation")
                        .HasColumnType("int");

                    b.Property<int>("HoursInSpace")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Paygrade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Astronauts");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanceValueToParentAU")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PlanetClass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CelestialBodies");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Launchpad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxSupportedWeightKg")
                        .HasColumnType("int");

                    b.Property<string>("PadCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PadCode")
                        .IsUnique();

                    b.ToTable("Launchpads");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Manager", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CelestialBodyId")
                        .HasColumnType("int");

                    b.Property<int?>("DurationHours")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LaunchDate")
                        .HasColumnType("date");

                    b.Property<int?>("LaunchpadId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RocketId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CelestialBodyId");

                    b.HasIndex("LaunchpadId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RocketId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.MissionAstronautAssignment", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<string>("AstronautId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MissionId", "AstronautId");

                    b.HasIndex("AstronautId");

                    b.ToTable("MissionAstronautAssignments");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.MissionScientistAssignment", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<string>("ScientistId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MissionId", "ScientistId");

                    b.HasIndex("ScientistId");

                    b.ToTable("MissionScientistAssignments");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Rocket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrewCapacity")
                        .HasColumnType("int");

                    b.Property<int>("FuelCapacityKg")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumberOfStages")
                        .HasColumnType("int");

                    b.Property<int>("PayloadCapacityKg")
                        .HasColumnType("int");

                    b.Property<int>("WeightKg")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rockets");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Scientist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Scientists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Astronaut", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", "User")
                        .WithOne("Astronaut")
                        .HasForeignKey("AarhusSpaceProgram.MissionManagement.Api.Models.Astronaut", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Manager", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", "User")
                        .WithOne("Manager")
                        .HasForeignKey("AarhusSpaceProgram.MissionManagement.Api.Models.Manager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", "TargetBody")
                        .WithMany("TargetedByMissions")
                        .HasForeignKey("CelestialBodyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Launchpad", "Launchpad")
                        .WithMany("Missions")
                        .HasForeignKey("LaunchpadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Manager", "Manager")
                        .WithMany("Missions")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Rocket", "Rocket")
                        .WithMany("Missions")
                        .HasForeignKey("RocketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Launchpad");

                    b.Navigation("Manager");

                    b.Navigation("Rocket");

                    b.Navigation("TargetBody");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.MissionAstronautAssignment", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Astronaut", "Astronaut")
                        .WithMany("MissionAssignments")
                        .HasForeignKey("AstronautId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", "Mission")
                        .WithMany("AstronautAssignments")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Astronaut");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.MissionScientistAssignment", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", "Mission")
                        .WithMany("ScientistAssignments")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Scientist", "Scientist")
                        .WithMany("MissionAssignments")
                        .HasForeignKey("ScientistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Scientist");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Scientist", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", "User")
                        .WithOne("Scientist")
                        .HasForeignKey("AarhusSpaceProgram.MissionManagement.Api.Models.Scientist", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.AspUser", b =>
                {
                    b.Navigation("Astronaut");

                    b.Navigation("Manager");

                    b.Navigation("Scientist");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Astronaut", b =>
                {
                    b.Navigation("MissionAssignments");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("TargetedByMissions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Launchpad", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Manager", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", b =>
                {
                    b.Navigation("AstronautAssignments");

                    b.Navigation("ScientistAssignments");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Rocket", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Scientist", b =>
                {
                    b.Navigation("MissionAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
