// <auto-generated />
using System;
using AarhusSpaceProgram.MissionManagement.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AarhusSpaceProgram.MissionManagement.Api.Migrations
{
    [DbContext(typeof(MissionManagementDbContext))]
    partial class MissionManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Astronaut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HoursInSimulation")
                        .HasColumnType("int");

                    b.Property<int>("HoursInSpace")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Paygrade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Astronauts");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanceValueAU")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PlanetClass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CelestialBodies");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Launchpad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxSupportedWeight")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Launchpads");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DurationHours")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LaunchDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.MissionAstronautAssignment", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("AstronautId")
                        .HasColumnType("int");

                    b.HasKey("MissionId", "AstronautId");

                    b.HasIndex("AstronautId");

                    b.ToTable("MissionAstronautAssignments");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.MissionScientistAssignment", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("ScientistId")
                        .HasColumnType("int");

                    b.HasKey("MissionId", "ScientistId");

                    b.HasIndex("ScientistId");

                    b.ToTable("MissionScientistAssignments");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Rocket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrewCapacity")
                        .HasColumnType("int");

                    b.Property<int>("FuelCapacityKg")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumberOfStages")
                        .HasColumnType("int");

                    b.Property<int>("PayloadCapacityKg")
                        .HasColumnType("int");

                    b.Property<int>("WeightKg")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rockets");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Scientist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Scientists");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.MissionAstronautAssignment", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Astronaut", "Astronaut")
                        .WithMany("MissionAssignments")
                        .HasForeignKey("AstronautId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", "Mission")
                        .WithMany("AstronautAssignments")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Astronaut");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.MissionScientistAssignment", b =>
                {
                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", "Mission")
                        .WithMany("ScientistAssignments")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.MissionManagement.Api.Models.Scientist", "Scientist")
                        .WithMany("MissionAssignments")
                        .HasForeignKey("ScientistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Scientist");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Astronaut", b =>
                {
                    b.Navigation("MissionAssignments");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.CelestialBody", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Mission", b =>
                {
                    b.Navigation("AstronautAssignments");

                    b.Navigation("ScientistAssignments");
                });

            modelBuilder.Entity("AarhusSpaceProgram.MissionManagement.Api.Models.Scientist", b =>
                {
                    b.Navigation("MissionAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
