version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${SQL_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql 
      - ./create-db-user.sql:/init/create-db-user.sql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "sqlserver", "-U", "sa", "-P", "${SQL_PASSWORD}", "-Q", "select 1"]
      interval: 10s
      start_period: 30s
      retries: 10

  db-init:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      sqlserver:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c", "sleep 5 && /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${SQL_PASSWORD} -i /init/create-db-user.sql"]
    environment:
      SA_PASSWORD: ${SQL_PASSWORD}
    volumes:
      - ./init.db.sh:/init/init-db.sh
      - ./create-db-user.sql:/init/create-db-user.sql
    restart: "no"

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: asplogs
    ports:
      - "27017:27017"

  api:
    build:
      context: .
      dockerfile: AarhusSpaceProgram.MissionManagement.Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MissionManagementASP;User=ASP;Password=MaAs3P4$$;TrustServerCertificate=True;
      - Serilog__WriteTo__0__Args__configureLogger__WriteTo__0__Args__databaseUrl=mongodb://mongodb:27017/asplogs
      - Serilog__WriteTo__0__Args__configureLogger__WriteTo__0__Args__collectionName=http_logs
      - Mongo__ConnectionString=mongodb://mongodb:27017
      - Mongo__DatabaseName=asplogs
      - Mongo_CollectionName=http_logs
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      mongodb: 
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: MissionLogGeneratorService/Dockerfile
    environment:
      - Mongo__ConnectionString=mongodb://mongodb:27017
      - Mongo__DatabaseName=asplogs
      - AspMissionManagementApiBaseUrl=http://api:8080
    depends_on:
      - api
      - mongodb

volumes:
  mssqldata: